import 'package:flutter/material.dart';

/* Text Check out out Community Channel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutoutCommunityChannelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Check out out Community Channel''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 10.0,
        fontFamily: 'Playfair Display',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 205, 66, 116),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
