import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedSometimesagenetictestfindsachangeinBRCA1orBRCA2thathasn.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedCARRIERCHILDREN50Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup25Widget3.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGeneticcounselingcanhelpapersonunderstandwhataVUSinBRCA.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedNONCARRIERPARENTWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedBRCA1andBRCA2mutationtestingcangiveseveralpossibleresul.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedWhatdoBRCA1andBRCA2genetictestresultsmeanWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedCARRIERPARENTWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedWithouttestingfamilymemberswhohavehadcanceritisuncertai.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedVariantofUncertainSignificanceVUSresultWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedComposition1Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup25Widget4.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedEACHCELLDIFFERSWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedAWAYTOUNDERSTANDBRCAINHERITANCEWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedBothmenandwomenwhoinheritaharmfulBRCA1orBRCA2variantwhe.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup25Widget5.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup26Widget3.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedAnegativetestresultcanhaveseveralmeaningsdependingonthe.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedWhatDoesAPositiveTestMeanWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedNONCARRIERCHILDREN50Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedBRCA1BRCA2Widget7.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedWhatDoesANegativeTestMeanWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness4widget/generated/GeneratedApositivetestresultindicatesthatapersonhasinheritedakno.dart';

/* Frame awareness-4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAwareness4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2155.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 2155.0,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.0, -1.0),
                                end: Alignment(0.0, 0.9999999999999998),
                                stops: [0.0, 1.0],
                                colors: [
                                  Color.fromARGB(255, 249, 155, 155),
                                  Color.fromARGB(209, 241, 199, 245)
                                ],
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 7.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 345.8785400390625,
                                    height: 44.0,
                                    child: GeneratedGroup25Widget3(),
                                  ),
                                  Positioned(
                                    left: 147.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 109.0,
                                    height: 44.0,
                                    child: GeneratedRectangle15Widget2(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 22.0,
                                    right: null,
                                    bottom: null,
                                    width: 288.0,
                                    height: 114.0,
                                    child: GeneratedBRCA1BRCA2Widget7(),
                                  ),
                                  Positioned(
                                    left: 7.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 359.0,
                                    height: 114.0,
                                    child:
                                        GeneratedWhatdoBRCA1andBRCA2genetictestresultsmeanWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 1.0,
                                    child: GeneratedLine6Widget(),
                                  ),
                                  Positioned(
                                    left: 289.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 1.0,
                                    child: GeneratedLine7Widget(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 190.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 81.0,
                                    child:
                                        GeneratedBRCA1andBRCA2mutationtestingcangiveseveralpossibleresul(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 286.0,
                                    right: null,
                                    bottom: null,
                                    width: 284.0,
                                    height: 50.0,
                                    child:
                                        GeneratedWhatDoesAPositiveTestMeanWidget(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 321.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 156.0,
                                    child:
                                        GeneratedApositivetestresultindicatesthatapersonhasinheritedakno(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 1539.0,
                                    right: null,
                                    bottom: null,
                                    width: 289.0,
                                    height: 50.0,
                                    child:
                                        GeneratedWhatDoesANegativeTestMeanWidget(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 1874.0,
                                    right: null,
                                    bottom: null,
                                    width: 285.0,
                                    height: 50.0,
                                    child:
                                        GeneratedVariantofUncertainSignificanceVUSresultWidget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 1574.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 189.0,
                                    child:
                                        GeneratedAnegativetestresultcanhaveseveralmeaningsdependingonthe(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 1755.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 103.0,
                                    child:
                                        GeneratedWithouttestingfamilymemberswhohavehadcanceritisuncertai(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 1933.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 103.0,
                                    child:
                                        GeneratedSometimesagenetictestfindsachangeinBRCA1orBRCA2thathasn(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 2034.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 50.0,
                                    child:
                                        GeneratedGeneticcounselingcanhelpapersonunderstandwhataVUSinBRCA(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 826.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 167.0,
                                    child:
                                        GeneratedBothmenandwomenwhoinheritaharmfulBRCA1orBRCA2variantwhe(),
                                  ),
                                  Positioned(
                                    left: 28.0,
                                    top: 508.0,
                                    right: null,
                                    bottom: null,
                                    width: 318.0,
                                    height: 270.0,
                                    child: GeneratedComposition1Widget(),
                                  ),
                                  Positioned(
                                    left: 133.0,
                                    top: 787.0,
                                    right: null,
                                    bottom: null,
                                    width: 119.0,
                                    height: 20.0,
                                    child: GeneratedEACHCELLDIFFERSWidget(),
                                  ),
                                  Positioned(
                                    left: 234.0,
                                    top: 1058.0,
                                    right: null,
                                    bottom: null,
                                    width: 121.0,
                                    height: 193.4479217529297,
                                    child: GeneratedGroup33Widget(),
                                  ),
                                  Positioned(
                                    left: 65.520263671875,
                                    top: 1251.4478759765625,
                                    right: null,
                                    bottom: null,
                                    width: 238.30203247070312,
                                    height: 107.36359405517578,
                                    child: GeneratedGroup34Widget(),
                                  ),
                                  Positioned(
                                    left: -5.999990940093994,
                                    top: 1059.0,
                                    right: null,
                                    bottom: null,
                                    width: 147.29934692382812,
                                    height: 193.61708068847656,
                                    child: GeneratedGroup39Widget(),
                                  ),
                                  Positioned(
                                    left: 248.327880859375,
                                    top: 1367.5166015625,
                                    right: null,
                                    bottom: null,
                                    width: 46.433597564697266,
                                    height: 102.5478515625,
                                    child: GeneratedGroup29Widget(),
                                  ),
                                  Positioned(
                                    left: 194.078125,
                                    top: 1368.33154296875,
                                    right: null,
                                    bottom: null,
                                    width: 46.433597564697266,
                                    height: 102.54784393310547,
                                    child: GeneratedGroup30Widget(),
                                  ),
                                  Positioned(
                                    left: 76.393310546875,
                                    top: 1368.7388916015625,
                                    right: null,
                                    bottom: null,
                                    width: 46.43381881713867,
                                    height: 102.5479736328125,
                                    child: GeneratedGroup36Widget(),
                                  ),
                                  Positioned(
                                    left: 132.365234375,
                                    top: 1367.5166015625,
                                    right: null,
                                    bottom: null,
                                    width: 46.433597564697266,
                                    height: 102.5479736328125,
                                    child: GeneratedGroup37Widget(),
                                  ),
                                  Positioned(
                                    left: 15.0,
                                    top: 1039.0,
                                    right: null,
                                    bottom: null,
                                    width: 108.0,
                                    height: 18.0,
                                    child: GeneratedCARRIERPARENTWidget(),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 1474.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 34.0,
                                    child: GeneratedCARRIERCHILDREN50Widget(),
                                  ),
                                  Positioned(
                                    left: 193.0,
                                    top: 1470.0,
                                    right: null,
                                    bottom: null,
                                    width: 118.0,
                                    height: 50.0,
                                    child:
                                        GeneratedNONCARRIERCHILDREN50Widget(),
                                  ),
                                  Positioned(
                                    left: 54.0,
                                    top: 1000.0,
                                    right: null,
                                    bottom: null,
                                    width: 253.0,
                                    height: 34.0,
                                    child:
                                        GeneratedAWAYTOUNDERSTANDBRCAINHERITANCEWidget(),
                                  ),
                                  Positioned(
                                    left: 218.0,
                                    top: 1039.0,
                                    right: null,
                                    bottom: null,
                                    width: 137.0,
                                    height: 18.0,
                                    child: GeneratedNONCARRIERPARENTWidget(),
                                  ),
                                  Positioned(
                                    left: 262.0,
                                    top: 2087.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup25Widget4(),
                                  ),
                                  Positioned(
                                    left: 92.0,
                                    top: 2112.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup25Widget5(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 568.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup26Widget3(),
            )
          ]),
    ));
  }
}
