import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle5Widget4.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedCONNECTWITHFACEBOOKWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedCONNECTWITHGOOGLEWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedEllipse1Widget6.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedSIGNUPWidget1.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedEMAILADDRESSWidget.dart';
import 'package:flutterapp/pinkapp/generatedsignuppagewidget/generated/GeneratedRectangle4Widget3.dart';

/* Frame Sign up page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignuppageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -53.0,
                top: -131.0,
                right: null,
                bottom: null,
                width: 431.0,
                height: 358.0,
                child: GeneratedEllipse1Widget6(),
              ),
              Positioned(
                left: 117.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 125.56462097167969,
                height: 64.0,
                child: GeneratedGroup7Widget2(),
              ),
              Positioned(
                left: 156.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 12.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 456.0,
                child: GeneratedRectangle1Widget7(),
              ),
              Positioned(
                left: 84.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 32.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 32.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 32.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 25.0,
                child: GeneratedRectangle2Widget7(),
              ),
              Positioned(
                left: 76.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 29.0,
                child: GeneratedEMAILADDRESSWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 205.00244140625,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 138.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 24.0,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 31.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 76.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 31.0,
                child: GeneratedRectangle5Widget4(),
              ),
              Positioned(
                left: 124.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 17.0,
                child: GeneratedCONNECTWITHFACEBOOKWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 17.0,
                child: GeneratedCONNECTWITHGOOGLEWidget(),
              ),
              Positioned(
                left: 178.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 23.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedSIGNUPWidget1(),
              ),
              Positioned(
                left: 117.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 14.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 85.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 25.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 25.0,
                child: GeneratedImage3Widget(),
              )
            ]),
      ),
    ));
  }
}
