import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedSELFEXAMINATIONWidget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedLetsstartWidget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedStep1Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedNowletsmovetostep2Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedOncesatisfiedmovetotheothersideDothesamewithyourleftbre.dart';
import 'package:flutterapp/pinkapp/generatedselfexam1widget/generated/GeneratedLookatyourbreastsinthemirrorRaiseyourrightarmpitfirstan.dart';

/* Frame Self exam 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelfexam1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 68.5,
                top: 66.5,
                right: null,
                bottom: null,
                width: 225.0,
                height: 34.0,
                child: GeneratedSELFEXAMINATIONWidget(),
              ),
              Positioned(
                left: 105.798828125,
                top: 92.5,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedLetsstartWidget(),
              ),
              Positioned(
                left: 148.298828125,
                top: 153.5,
                right: null,
                bottom: null,
                width: 65.0,
                height: 34.0,
                child: GeneratedStep1Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 98.0,
                child:
                    GeneratedLookatyourbreastsinthemirrorRaiseyourrightarmpitfirstan(),
              ),
              Positioned(
                left: 29.298828125,
                top: 471.5,
                right: null,
                bottom: null,
                width: 303.0,
                height: 50.0,
                child:
                    GeneratedOncesatisfiedmovetotheothersideDothesamewithyourleftbre(),
              ),
              Positioned(
                left: 55.1494140625,
                top: 584.4225463867188,
                right: null,
                bottom: null,
                width: 249.701171875,
                height: 34.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 83.298828125,
                top: 589.4225463867188,
                right: null,
                bottom: null,
                width: 195.0,
                height: 26.0,
                child: GeneratedNowletsmovetostep2Widget(),
              ),
              Positioned(
                left: 118.298828125,
                top: 200.875,
                right: null,
                bottom: null,
                width: 123.0,
                height: 136.75,
                child: GeneratedImage7Widget(),
              )
            ]),
      ),
    ));
  }
}
