import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedbotwidget/generated/GeneratedSWMiconsduotonemessagesquareWidget.dart';

/* Frame bot
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBotWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 0.3296875059604645, 1.0],
            colors: [
              Color.fromARGB(255, 249, 155, 155),
              Color.fromARGB(170, 246, 161, 172),
              Color.fromARGB(0, 240, 175, 207)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 300.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 243.0,
                child: GeneratedSWMiconsduotonemessagesquareWidget(),
              )
            ]),
      ),
    ));
  }
}
