import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedToneWidget7.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedSWMiconsduotonemessagesquareWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedWANTSAWARENESSWidget.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedUNDERGOINGTREATMENTWidget.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/pinkapp/generatedbot2widget/generated/GeneratedBREASTCANCERSURVIVORWidget.dart';

/* Frame bot-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBot2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 0.3296875059604645, 1.0],
            colors: [
              Color.fromARGB(255, 249, 155, 155),
              Color.fromARGB(170, 246, 161, 172),
              Color.fromARGB(0, 240, 175, 207)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.65;

                  final double height = constraints.maxHeight * 0.7625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7888888888888889,
                        y: constraints.maxHeight * 0.1390625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSWMiconsduotonemessagesquareWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.4388889312744141;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      158.00001525878906;

                  double percentHeight = 0.509375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 326.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6833333333333333,
                        translateY: constraints.maxHeight * 0.2765625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedToneWidget7())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2861111111111111;

                  final double height = constraints.maxHeight * 0.0671875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3055555555555556,
                        y: constraints.maxHeight * 0.3734375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle12Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2861111111111111;

                  final double height = constraints.maxHeight * 0.0671875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3055555555555556,
                        y: constraints.maxHeight * 0.5546875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle13Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2861111111111111;

                  final double height = constraints.maxHeight * 0.0671875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3055555555555556,
                        y: constraints.maxHeight * 0.465625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle14Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2638888888888889;

                  final double height = constraints.maxHeight * 0.0234375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3194444444444444,
                        y: constraints.maxHeight * 0.396875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWANTSAWARENESSWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18888888888888888;

                  final double height = constraints.maxHeight * 0.04375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3527777777777778,
                        y: constraints.maxHeight * 0.4796875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUNDERGOINGTREATMENTWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.225;

                  final double height = constraints.maxHeight * 0.04375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3388888888888889,
                        y: constraints.maxHeight * 0.56875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBREASTCANCERSURVIVORWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
