import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedForagooddietandcalmingmusicWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedIstockphoto1314692730612x612removebgpreview1Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedGroup24Widget3.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedForagooddietandcalmingmusicWidget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedInstudiesofwomenwithbreastcanceryogahasbeenshowntoreduc.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedDirgaPranayamaWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedEncouragesfullandcompletebreathingandhelpsreleasemuscle.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedTakespressureoffthespineandneckaidscirculationandrelaxa.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedHelpsstretchthehipsthighsandbackmuscleswhilerelaxingthe.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedViparitaKaraniWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedIfyouhavecancerfatigueanxietyfeelingsofdepressionafully.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedImagesremovebgpreview11Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedDownload__1_removebgpreview1Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedUttanasanaWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedDownloadremovebgpreview1Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedImage22Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedSavasanaWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedGroup27Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedImagesremovebgpreview1Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedStretchesthehipshamstringsandcalvesrelievingtensioninth.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedBalasanaWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedYOGAWidget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedHelpscalmthemindandrelievefeelingsofstressWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment1widget/generated/GeneratedGroup25Widget2.dart';

/* Frame Treatment-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTreatment1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2095.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1824.0,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.0, -1.0),
                                end: Alignment(0.0, 0.9999999999999998),
                                stops: [0.0, 1.0],
                                colors: [
                                  Color.fromARGB(255, 249, 155, 155),
                                  Color.fromARGB(204, 241, 199, 245)
                                ],
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 0.0,
                                    top: 83.0,
                                    right: null,
                                    bottom: null,
                                    width: 102.0,
                                    height: 1.0,
                                    child: GeneratedLine4Widget1(),
                                  ),
                                  Positioned(
                                    left: 258.0,
                                    top: 83.0,
                                    right: null,
                                    bottom: null,
                                    width: 102.0,
                                    height: 1.0,
                                    child: GeneratedLine5Widget1(),
                                  ),
                                  Positioned(
                                    left: 7.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 345.8785400390625,
                                    height: 44.0,
                                    child: GeneratedGroup25Widget1(),
                                  ),
                                  Positioned(
                                    left: 63.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 78.0,
                                    height: 44.0,
                                    child: GeneratedRectangle15Widget1(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 27.0,
                                    right: null,
                                    bottom: null,
                                    width: 291.0,
                                    height: 117.0,
                                    child: GeneratedYOGAWidget2(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 168.0,
                                    right: null,
                                    bottom: null,
                                    width: 307.0,
                                    height: 558.0,
                                    child:
                                        GeneratedInstudiesofwomenwithbreastcanceryogahasbeenshowntoreduc(),
                                  ),
                                  Positioned(
                                    left: 8.0,
                                    top: 549.0,
                                    right: null,
                                    bottom: null,
                                    width: 218.0,
                                    height: 298.0,
                                    child:
                                        GeneratedEncouragesfullandcompletebreathingandhelpsreleasemuscle(),
                                  ),
                                  Positioned(
                                    left: 1.0,
                                    top: 746.0,
                                    right: null,
                                    bottom: null,
                                    width: 218.0,
                                    height: 298.0,
                                    child:
                                        GeneratedHelpsstretchthehipsthighsandbackmuscleswhilerelaxingthe(),
                                  ),
                                  Positioned(
                                    left: 3.0,
                                    top: 943.0,
                                    right: null,
                                    bottom: null,
                                    width: 218.0,
                                    height: 298.0,
                                    child:
                                        GeneratedStretchesthehipshamstringsandcalvesrelievingtensioninth(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 1168.0,
                                    right: null,
                                    bottom: null,
                                    width: 218.0,
                                    height: 298.0,
                                    child:
                                        GeneratedTakespressureoffthespineandneckaidscirculationandrelaxa(),
                                  ),
                                  Positioned(
                                    left: 4.0,
                                    top: 1366.0,
                                    right: null,
                                    bottom: null,
                                    width: 218.0,
                                    height: 298.0,
                                    child:
                                        GeneratedHelpscalmthemindandrelievefeelingsofstressWidget(),
                                  ),
                                  Positioned(
                                    left: 212.0,
                                    top: 1408.0,
                                    right: null,
                                    bottom: null,
                                    width: 146.0,
                                    height: 173.0,
                                    child:
                                        GeneratedDownload__1_removebgpreview1Widget(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 620.0,
                                    right: null,
                                    bottom: null,
                                    width: 90.0,
                                    height: 119.0,
                                    child:
                                        GeneratedImagesremovebgpreview1Widget(),
                                  ),
                                  Positioned(
                                    left: 193.0,
                                    top: 794.0,
                                    right: null,
                                    bottom: null,
                                    width: 168.0,
                                    height: 164.0,
                                    child:
                                        GeneratedIstockphoto1314692730612x612removebgpreview1Widget(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 999.0,
                                    right: null,
                                    bottom: null,
                                    width: 89.0,
                                    height: 208.0,
                                    child:
                                        GeneratedImagesremovebgpreview11Widget(),
                                  ),
                                  Positioned(
                                    left: 216.0,
                                    top: 1239.0,
                                    right: null,
                                    bottom: null,
                                    width: 137.0,
                                    height: 127.0,
                                    child:
                                        GeneratedDownloadremovebgpreview1Widget(),
                                  ),
                                  Positioned(
                                    left: 17.0,
                                    top: 149.0,
                                    right: null,
                                    bottom: null,
                                    width: 329.0,
                                    height: 166.0,
                                    child: GeneratedImage22Widget(),
                                  ),
                                  Positioned(
                                    left: 84.0,
                                    top: 577.0,
                                    right: null,
                                    bottom: null,
                                    width: 196.0,
                                    height: 45.0,
                                    child: GeneratedDirgaPranayamaWidget(),
                                  ),
                                  Positioned(
                                    left: 81.0,
                                    top: 782.0,
                                    right: null,
                                    bottom: null,
                                    width: 199.0,
                                    height: 48.0,
                                    child: GeneratedBalasanaWidget(),
                                  ),
                                  Positioned(
                                    left: 83.0,
                                    top: 1407.0,
                                    right: null,
                                    bottom: null,
                                    width: 199.0,
                                    height: 48.0,
                                    child: GeneratedSavasanaWidget(),
                                  ),
                                  Positioned(
                                    left: 83.0,
                                    top: 1185.0,
                                    right: null,
                                    bottom: null,
                                    width: 196.0,
                                    height: 45.0,
                                    child: GeneratedViparitaKaraniWidget(),
                                  ),
                                  Positioned(
                                    left: 72.0,
                                    top: 970.0,
                                    right: null,
                                    bottom: null,
                                    width: 199.0,
                                    height: 48.0,
                                    child: GeneratedUttanasanaWidget(),
                                  ),
                                  Positioned(
                                    left: 15.0,
                                    top: 1592.0,
                                    right: null,
                                    bottom: null,
                                    width: 319.0,
                                    height: 152.0,
                                    child:
                                        GeneratedIfyouhavecancerfatigueanxietyfeelingsofdepressionafully(),
                                  ),
                                  Positioned(
                                    left: 67.0,
                                    top: 2075.0,
                                    right: null,
                                    bottom: null,
                                    width: 161.0,
                                    height: 17.0,
                                    child:
                                        GeneratedForagooddietandcalmingmusicWidget(),
                                  ),
                                  Positioned(
                                    left: 238.0,
                                    top: 2070.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup25Widget2(),
                                  ),
                                  Positioned(
                                    left: 103.0,
                                    top: 1778.0,
                                    right: null,
                                    bottom: null,
                                    width: 164.0,
                                    height: 18.0,
                                    child:
                                        GeneratedForagooddietandcalmingmusicWidget1(),
                                  ),
                                  Positioned(
                                    left: 268.0,
                                    top: 1773.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup27Widget1(),
                                  ),
                                  Positioned(
                                    left: 90.0,
                                    top: 1798.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup28Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 567.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup24Widget3(),
            )
          ]),
    ));
  }
}
