import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedTodaysupportgroupmeetingat5pmLinkxyzjjsigWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedShapeWidget13.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedIshitaRajWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedLifegaveuslemonsletstakecareofthemCheckregularyonyourbr.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedSYMPTOMSWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedShapeWidget15.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedShapeWidget14.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedExploreWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle21Widget3.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedAishaniGhoshWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedShapeWidget12.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedIshiSaxenaWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedSoumiyaChadhaWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedVector8Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedABOUTWidget1.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedCOMMMUNITYWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedBRCA1BRCA2Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedNewPostWidget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedHellobeautifulladiesjustgotmyfirstmonogramdoneFeltgoodt.dart';
import 'package:flutterapp/pinkapp/generatedcommunitypagewidget/generated/GeneratedbreastcancerawarenessWidget.dart';

/* Frame Community Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCommunityPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedCommunityPage1Widget'),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1478.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1478.0,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.0, -1.0),
                                end: Alignment(0.0, 0.9999999999999998),
                                stops: [0.0, 1.0],
                                colors: [
                                  Color.fromARGB(255, 249, 155, 155),
                                  Color.fromARGB(191, 241, 199, 245)
                                ],
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 0.0,
                                    top: 679.1549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 270.0,
                                    child: GeneratedRectangle17Widget1(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 308.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 270.0,
                                    child: GeneratedRectangle21Widget3(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 1056.1549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 270.0,
                                    child: GeneratedRectangle19Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 360.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 185.0,
                                    child: GeneratedRectangle16Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 731.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 185.0,
                                    child: GeneratedRectangle18Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 1108.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 185.0,
                                    child: GeneratedRectangle20Widget(),
                                  ),
                                  Positioned(
                                    left: 8.5,
                                    top: 309.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 51.0,
                                    child: GeneratedEllipse10Widget(),
                                  ),
                                  Positioned(
                                    left: 8.5,
                                    top: 680.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 51.0,
                                    child: GeneratedEllipse11Widget(),
                                  ),
                                  Positioned(
                                    left: 8.5,
                                    top: 1057.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 51.0,
                                    child: GeneratedEllipse12Widget(),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 323.0,
                                    right: null,
                                    bottom: null,
                                    width: 130.0,
                                    height: 25.0,
                                    child: GeneratedSoumiyaChadhaWidget(),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 694.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 112.0,
                                    height: 25.0,
                                    child: GeneratedAishaniGhoshWidget(),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 1071.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 73.0,
                                    height: 25.0,
                                    child: GeneratedIshitaRajWidget(),
                                  ),
                                  Positioned(
                                    left: 76.92529296875,
                                    top: 551.5,
                                    right: null,
                                    bottom: null,
                                    width: 22.0,
                                    height: 19.0,
                                    child: GeneratedComponent3Widget(),
                                  ),
                                  Positioned(
                                    left: 70.0,
                                    top: 1301.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 22.0,
                                    height: 19.0,
                                    child: GeneratedComponent4Widget(),
                                  ),
                                  Positioned(
                                    left: 71.333984375,
                                    top: 923.59130859375,
                                    right: null,
                                    bottom: null,
                                    width: 22.0,
                                    height: 19.0,
                                    child: GeneratedComponent5Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.05;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          18.0;

                                      double percentHeight =
                                          0.010825439783491205;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          16.0;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.09583333333333334,
                                            translateY: constraints.maxHeight *
                                                0.6248926309835927,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedShapeWidget12())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.05;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          18.0;

                                      double percentHeight =
                                          0.010825439783491205;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          16.0;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.07083333333333333,
                                            translateY: constraints.maxHeight *
                                                0.8806866760666864,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedShapeWidget13())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.05;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          18.0;

                                      double percentHeight =
                                          0.010825439783491205;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          16.0;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.09583333333333334,
                                            translateY: constraints.maxHeight *
                                                0.37415426251691475,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedShapeWidget14())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.05;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          18.0;

                                      double percentHeight =
                                          0.010825439783491205;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          16.0;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.6138888888888889,
                                            translateY: constraints.maxHeight *
                                                0.37483085250338294,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedShapeWidget15())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 39.287109375,
                                    top: 406.5,
                                    right: null,
                                    bottom: null,
                                    width: 273.0,
                                    height: 94.0,
                                    child:
                                        GeneratedHellobeautifulladiesjustgotmyfirstmonogramdoneFeltgoodt(),
                                  ),
                                  Positioned(
                                    left: 60.0,
                                    top: 784.6549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 242.0,
                                    height: 71.0,
                                    child:
                                        GeneratedTodaysupportgroupmeetingat5pmLinkxyzjjsigWidget(),
                                  ),
                                  Positioned(
                                    left: 5.880859375,
                                    top: 1131.1549072265625,
                                    right: null,
                                    bottom: null,
                                    width: 344.0,
                                    height: 97.0,
                                    child:
                                        GeneratedLifegaveuslemonsletstakecareofthemCheckregularyonyourbr(),
                                  ),
                                  Positioned(
                                    left: 100.0,
                                    top: 1239.0,
                                    right: null,
                                    bottom: null,
                                    width: 165.0,
                                    height: 24.0,
                                    child:
                                        GeneratedbreastcancerawarenessWidget(),
                                  ),
                                  Positioned(
                                    left: 12.5,
                                    top: 211.0,
                                    right: null,
                                    bottom: null,
                                    width: 335.0,
                                    height: 0.0,
                                    child: GeneratedVector8Widget(),
                                  ),
                                  Positioned(
                                    left: 15.0,
                                    top: 46.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 64.0,
                                    child: GeneratedEllipse9Widget(),
                                  ),
                                  Positioned(
                                    left: 15.0,
                                    top: 156.4225311279297,
                                    right: null,
                                    bottom: null,
                                    width: 91.0,
                                    height: 34.0,
                                    child: GeneratedRectangle14Widget(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 163.4225311279297,
                                    right: null,
                                    bottom: null,
                                    width: 65.0,
                                    height: 22.0,
                                    child: GeneratedNewPostWidget(),
                                  ),
                                  Positioned(
                                    left: 17.0,
                                    top: 114.49952697753906,
                                    right: null,
                                    bottom: null,
                                    width: 128.0,
                                    height: 34.0,
                                    child: GeneratedIshiSaxenaWidget(),
                                  ),
                                  Positioned(
                                    left: 17.0,
                                    top: 219.0,
                                    right: null,
                                    bottom: null,
                                    width: 90.0,
                                    height: 37.0,
                                    child: GeneratedExploreWidget(),
                                  ),
                                  Positioned(
                                    left: 258.84393310546875,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 94.8785400390625,
                                    height: 49.0,
                                    child: GeneratedCOMMMUNITYWidget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 98.0,
                                    height: 46.0,
                                    child: GeneratedBRCA1BRCA2Widget(),
                                  ),
                                  Positioned(
                                    left: 60.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 49.0,
                                    child: GeneratedSYMPTOMSWidget(),
                                  ),
                                  Positioned(
                                    left: 12.637651443481445,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 48.72469711303711,
                                    height: 49.0,
                                    child: GeneratedABOUTWidget1(),
                                  ),
                                  Positioned(
                                    left: 253.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 107.0,
                                    height: 44.0,
                                    child: GeneratedRectangle14Widget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 569.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup25Widget(),
            )
          ]),
    ));
  }
}
