import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedAfriendlyremindertotakecareofyourselfWidget.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/pinkapp/generatedlandingpagewidget/generated/GeneratedLayer141Widget.dart';

/* Frame landing page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLandingpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 74.5,
                top: 179.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 194.0,
                child: GeneratedLayer141Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 125.56462097167969,
                height: 64.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 12.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 42.95295715332031,
                top: 400.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 22.0,
                child: GeneratedAfriendlyremindertotakecareofyourselfWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 106.43540954589844,
                height: 24.0,
                child: GeneratedGroup7Widget1(),
              )
            ]),
      ),
    ));
  }
}
