import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedPatientWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedVector3Widget1.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedExperienceWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedEllipse3Widget4.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedDrSelviRadhakrishnaWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedImage28Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedGroup25Widget7.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedDrSelviRadhakrishnaisaleadingconsultantoncoplasticsurge.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedBreastsWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedVector4Widget1.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedGroup22Widget1.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedIconsCommentWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedVectorWidget92.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/Generated50Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedRectangle180Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedGroup23Widget1.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedRatingWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedRectangle179Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor2widget/generated/GeneratedGroup24Widget4.dart';

/* Frame doctor 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctor2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 759.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 249, 155, 155),
              Color.fromARGB(201, 241, 199, 245)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 7.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 311.0,
                child: GeneratedGroup22Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 350.0,
                child: GeneratedImage28Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 26.0,
                child: GeneratedDrSelviRadhakrishnaWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 15.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 20.0,
                child: GeneratedBreastsWidget(),
              ),
              Positioned(
                left: 82.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 3.0,
                child: GeneratedEllipse3Widget4(),
              ),
              Positioned(
                left: 16.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 122.0,
                child:
                    GeneratedDrSelviRadhakrishnaisaleadingconsultantoncoplasticsurge(),
              ),
              Positioned(
                left: 36.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 29.0,
                child: GeneratedExperienceWidget(),
              ),
              Positioned(
                left: 270.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 29.0,
                child: GeneratedRatingWidget(),
              ),
              Positioned(
                left: 158.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 29.0,
                child: GeneratedPatientWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 56.0,
                child: GeneratedRectangle179Widget(),
              ),
              Positioned(
                left: 130.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 54.0,
                child: GeneratedVector3Widget1(),
              ),
              Positioned(
                left: 239.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 0.0,
                height: 54.0,
                child: GeneratedVector4Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 37.0,
                child: GeneratedGroup23Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 40.0,
                child: GeneratedGroup24Widget4(),
              ),
              Positioned(
                left: 166.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 36.0,
                child: GeneratedGroup25Widget7(),
              ),
              Positioned(
                left: 279.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 41.0,
                child: Generated50Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 56.0,
                child: GeneratedRectangle180Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedIconsCommentWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.019444444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 7.0;

                  double percentHeight = 0.020262596321357254;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.379310607910156;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.041666666666666664,
                        translateY: constraints.maxHeight * 0.01844532279314888,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget92())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
