import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedGroup24Widget2.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedToreadmoreaboutBRCA1andBRCA2testsWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedAharmfulvariantinBRCA1orBRCA2canbeinheritedfromeitherpa.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedHowIsBRCAGenesInheritedWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedRoleofbrcamutationsinbreastcancersurvival4158206colorV1.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedWhatAreBRCAGenesWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedGroup24Widget1.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedMutationsintheBRCA1BRCA2geneareassociatedwithanincrease.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedBRCA1BReastCAncergene1andBRCA2BReastCAncergene2aregenes.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/pinkapp/generatedawareness3widget/generated/GeneratedBRCA1BRCA2Widget4.dart';

/* Frame awareness-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAwareness3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1651.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1651.0,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.0, -1.0),
                                end: Alignment(0.0, 0.9999999999999998),
                                stops: [0.0, 1.0],
                                colors: [
                                  Color.fromARGB(255, 249, 155, 155),
                                  Color.fromARGB(204, 241, 199, 245)
                                ],
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 7.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 345.8785400390625,
                                    height: 44.0,
                                    child: GeneratedGroup5Widget1(),
                                  ),
                                  Positioned(
                                    left: 147.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 109.0,
                                    height: 44.0,
                                    child: GeneratedRectangle14Widget5(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 22.0,
                                    right: null,
                                    bottom: null,
                                    width: 288.0,
                                    height: 114.0,
                                    child: GeneratedBRCA1BRCA2Widget4(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 1.0,
                                    child: GeneratedLine4Widget(),
                                  ),
                                  Positioned(
                                    left: 289.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 1.0,
                                    child: GeneratedLine5Widget(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 105.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 151.0,
                                    child:
                                        GeneratedMutationsintheBRCA1BRCA2geneareassociatedwithanincrease(),
                                  ),
                                  Positioned(
                                    left: 12.0,
                                    top: 273.0,
                                    right: null,
                                    bottom: null,
                                    width: 335.0,
                                    height: 315.0,
                                    child:
                                        GeneratedRoleofbrcamutationsinbreastcancersurvival4158206colorV1(),
                                  ),
                                  Positioned(
                                    left: 60.0,
                                    top: 607.0,
                                    right: null,
                                    bottom: null,
                                    width: 236.0,
                                    height: 71.0,
                                    child: GeneratedWhatAreBRCAGenesWidget(),
                                  ),
                                  Positioned(
                                    left: 63.0,
                                    top: 1089.0,
                                    right: null,
                                    bottom: null,
                                    width: 236.0,
                                    height: 71.0,
                                    child:
                                        GeneratedHowIsBRCAGenesInheritedWidget(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 661.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 370.0,
                                    child:
                                        GeneratedBRCA1BReastCAncergene1andBRCA2BReastCAncergene2aregenes(),
                                  ),
                                  Positioned(
                                    left: 23.0,
                                    top: 1158.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 395.0,
                                    child:
                                        GeneratedAharmfulvariantinBRCA1orBRCA2canbeinheritedfromeitherpa(),
                                  ),
                                  Positioned(
                                    left: 79.0,
                                    top: 1588.0,
                                    right: null,
                                    bottom: null,
                                    width: 207.0,
                                    height: 17.0,
                                    child:
                                        GeneratedToreadmoreaboutBRCA1andBRCA2testsWidget(),
                                  ),
                                  Positioned(
                                    left: 275.0,
                                    top: 1583.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup24Widget(),
                                  ),
                                  Positioned(
                                    left: 79.0,
                                    top: 1608.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup24Widget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 567.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup24Widget2(),
            )
          ]),
    ));
  }
}
