import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedImage12Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedTextWidget5.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedSometimeswhenwerestressedoutrestlesssadorevenhappyallwe.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedMUSICWidget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedLine8Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedCLICKHEREWidget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedDownloadremovebgpreview2Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedTextWidget3.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedSpotifyplaylisttohelpyougetintoarelaxedstateofmindWidge.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedTextWidget4.dart';
import 'package:flutterapp/pinkapp/generatedtreatment3widget/generated/GeneratedGroup26Widget1.dart';

/* Frame Treatment-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTreatment3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 643.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 249, 155, 155),
              Color.fromARGB(211, 241, 199, 245)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 186.1484375,
                top: 420.0,
                right: null,
                bottom: null,
                width: 2.0,
                height: 26.0,
                child: GeneratedTextWidget3(),
              ),
              Positioned(
                left: 186.1484375,
                top: 475.0,
                right: null,
                bottom: null,
                width: 2.0,
                height: 50.0,
                child: GeneratedTextWidget4(),
              ),
              Positioned(
                left: 134.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 34.0,
                child: GeneratedTextWidget5(),
              ),
              Positioned(
                left: 24.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 152.0,
                child:
                    GeneratedSometimeswhenwerestressedoutrestlesssadorevenhappyallwe(),
              ),
              Positioned(
                left: 24.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 345.8785400390625,
                height: 44.0,
                child: GeneratedGroup26Widget1(),
              ),
              Positioned(
                left: 282.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 44.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 22.000003814697266,
                right: null,
                bottom: null,
                width: 291.0,
                height: 117.0,
                child: GeneratedMUSICWidget1(),
              ),
              Positioned(
                left: 252.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 1.0,
                child: GeneratedLine8Widget1(),
              ),
              Positioned(
                left: 25.396486282348633,
                top: 112.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 45.0,
                child:
                    GeneratedSpotifyplaylisttohelpyougetintoarelaxedstateofmindWidge(),
              ),
              Positioned(
                left: 0.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 203.77978515625,
                top: 258.0,
                right: null,
                bottom: null,
                width: 142.22021484375,
                height: 42.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: -44.46875,
                top: 164.0,
                right: null,
                bottom: null,
                width: 268.46875,
                height: 260.0,
                child: GeneratedDownloadremovebgpreview2Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 249.25,
                right: null,
                bottom: null,
                width: 59.0,
                height: 59.5,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 203.12631225585938,
                top: 240.0,
                right: null,
                bottom: null,
                width: 145.5271453857422,
                height: 80.0,
                child: GeneratedCLICKHEREWidget1(),
              ),
              Positioned(
                left: 153.54306030273438,
                top: 246.2216339111328,
                right: null,
                bottom: null,
                width: 61.0,
                height: 58.5,
                child: GeneratedImage12Widget(),
              )
            ]),
      ),
    ));
  }
}
