import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedImage9Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedSELFEXAMINATIONWidget2.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedStep3Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedNowletsmovetostep4Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedUseyourrighthandtofeelyourleftbreastandthenyourlefthand.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedUseafirmsmoothtouchwiththefirstthreefingerpadsofyourhan.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedRectangle2Widget5.dart';
import 'package:flutterapp/pinkapp/generatedselfexam3widget/generated/GeneratedRectangle1Widget5.dart';

/* Frame Self exam 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelfexam3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget5(),
              ),
              Positioned(
                left: 68.5,
                top: 66.5,
                right: null,
                bottom: null,
                width: 225.0,
                height: 34.0,
                child: GeneratedSELFEXAMINATIONWidget2(),
              ),
              Positioned(
                left: 147.298828125,
                top: 153.5,
                right: null,
                bottom: null,
                width: 67.0,
                height: 34.0,
                child: GeneratedStep3Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 74.0,
                child:
                    GeneratedUseyourrighthandtofeelyourleftbreastandthenyourlefthand(),
              ),
              Positioned(
                left: 4.298828125,
                top: 447.5,
                right: null,
                bottom: null,
                width: 353.0,
                height: 98.0,
                child:
                    GeneratedUseafirmsmoothtouchwiththefirstthreefingerpadsofyourhan(),
              ),
              Positioned(
                left: 55.1494140625,
                top: 584.4225463867188,
                right: null,
                bottom: null,
                width: 249.701171875,
                height: 34.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 83.298828125,
                top: 589.4225463867188,
                right: null,
                bottom: null,
                width: 194.0,
                height: 26.0,
                child: GeneratedNowletsmovetostep4Widget(),
              ),
              Positioned(
                left: 115.298828125,
                top: 211.25,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedImage9Widget(),
              )
            ]),
      ),
    ));
  }
}
