import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedDIETWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedGroup26Widget6.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedImage24Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedGroup30Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedAllowyourbodythenutrientsitneedstofightcancerWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedHorizontallinedesignpng11552249443hrz3ortnmwremovebgpre1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedWhatshouldIeatWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedPhytonutrientssupporthumanhealthandarefoundinplantbased.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedGroup29Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle2Widget10.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedImage23Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedGroup26Widget7.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedLine7Widget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedStayhydratedWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedCalmingmusicWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedFocusonnutrientsWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedDontforgetproteinWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedHorizontallinedesignpng11552249443hrz3ortnmwremovebgpre.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedWhetheryourenewlydiagnosedwithbreastcanceroryourefacing.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle22Widget4.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedGetenoughcaloriesWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatment2widget/generated/GeneratedRectangle24Widget1.dart';

/* Frame Treatment-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTreatment2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1775.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1775.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 1.0],
                          colors: [
                            Color.fromARGB(255, 255, 175, 175),
                            Color.fromARGB(204, 241, 199, 245)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 24.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 345.8785400390625,
                              height: 44.0,
                              child: GeneratedGroup26Widget6(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 44.0,
                              child: GeneratedRectangle16Widget3(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 22.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 117.0,
                              child: GeneratedDIETWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 78.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 1.0,
                              child: GeneratedLine6Widget2(),
                            ),
                            Positioned(
                              left: 258.0,
                              top: 78.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 1.0,
                              child: GeneratedLine7Widget2(),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 172.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 407.0,
                              child:
                                  GeneratedPhytonutrientssupporthumanhealthandarefoundinplantbased(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 72.0,
                              child:
                                  GeneratedAllowyourbodythenutrientsitneedstofightcancerWidget(),
                            ),
                            Positioned(
                              left: 228.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 115.0,
                              child: GeneratedImage23Widget(),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 75.0,
                              child: GeneratedGroup26Widget7(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 1220.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 59.0,
                              child: GeneratedRectangle22Widget4(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 1320.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 59.0,
                              child: GeneratedRectangle23Widget2(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 1430.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 59.0,
                              child: GeneratedRectangle24Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 1540.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 59.0,
                              child: GeneratedRectangle25Widget1(),
                            ),
                            Positioned(
                              left: 103.0,
                              top: 1230.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 42.0,
                              child: GeneratedStayhydratedWidget(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 1330.0,
                              right: null,
                              bottom: null,
                              width: 228.0,
                              height: 42.0,
                              child: GeneratedGetenoughcaloriesWidget(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 1440.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 42.0,
                              child: GeneratedFocusonnutrientsWidget(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 1550.0,
                              right: null,
                              bottom: null,
                              width: 229.0,
                              height: 42.0,
                              child: GeneratedDontforgetproteinWidget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 678.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 242.0,
                              child:
                                  GeneratedWhetheryourenewlydiagnosedwithbreastcanceroryourefacing(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 1600.0,
                              right: null,
                              bottom: null,
                              width: 330.0,
                              height: 82.0,
                              child:
                                  GeneratedHorizontallinedesignpng11552249443hrz3ortnmwremovebgpre(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 1138.0,
                              right: null,
                              bottom: null,
                              width: 330.0,
                              height: 82.0,
                              child:
                                  GeneratedHorizontallinedesignpng11552249443hrz3ortnmwremovebgpre1(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 965.0,
                              right: null,
                              bottom: null,
                              width: 353.37213134765625,
                              height: 147.7375030517578,
                              child: GeneratedRectangle2Widget10(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 925.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 175.0,
                              child: GeneratedWhatshouldIeatWidget(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 1699.0,
                              right: null,
                              bottom: null,
                              width: 164.0,
                              height: 18.0,
                              child: GeneratedCalmingmusicWidget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 1694.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 25.0,
                              child: GeneratedGroup29Widget1(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 1719.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 25.0,
                              child: GeneratedGroup30Widget1(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 114.0,
                              child: GeneratedImage24Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
