import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedCheckoutourbreastspcialistsectiontofindthebestoncologis.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedImage11Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedYoucangobackandscheduleyournextmonthlyreminderWidget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedSELFEXAMINATIONWidget1.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedIfyouhaveanychangesmentionedinthepreviousstepsdontpanic.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedBynowyouhaveafeelofyourbreastsIfyouaresatisfiedwellandg.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedStep4Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam4widget/generated/GeneratedRectangle1Widget3.dart';

/* Frame Self exam 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelfexam4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 68.5,
                top: 66.5,
                right: null,
                bottom: null,
                width: 225.0,
                height: 34.0,
                child: GeneratedSELFEXAMINATIONWidget1(),
              ),
              Positioned(
                left: 147.298828125,
                top: 153.5,
                right: null,
                bottom: null,
                width: 67.0,
                height: 34.0,
                child: GeneratedStep4Widget(),
              ),
              Positioned(
                left: 26.1484375,
                top: 408.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 50.0,
                child:
                    GeneratedYoucangobackandscheduleyournextmonthlyreminderWidget(),
              ),
              Positioned(
                left: 29.1484375,
                top: 360.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 74.0,
                child:
                    GeneratedBynowyouhaveafeelofyourbreastsIfyouaresatisfiedwellandg(),
              ),
              Positioned(
                left: -42.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 457.0,
                height: 95.0,
                child:
                    GeneratedIfyouhaveanychangesmentionedinthepreviousstepsdontpanic(),
              ),
              Positioned(
                left: 116.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedImage11Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 29.0,
                child:
                    GeneratedCheckoutourbreastspcialistsectiontofindthebestoncologis(),
              ),
              Positioned(
                left: 0.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 28.0,
                child: GeneratedGroup10Widget(),
              )
            ]),
      ),
    ));
  }
}
