import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1317Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1310Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedEllipse13Widget3.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedBreastsWidget3.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedViewallWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedFindYourNearestOncologistWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedMedicinesWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedImage26Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1309Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1318Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1316Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedTopDoctorsWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedSurgeonWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup27Widget2.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedConsultationWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedImage27Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1315Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedHospitalsWidget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedGroup1311Widget.dart';
import 'package:flutterapp/pinkapp/generateddoctor1widget/generated/GeneratedImage25Widget.dart';

/* Frame doctor-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctor1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 709.0,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment(9.693111291397827e-8, -0.9999999997865677),
                  end: Alignment(-0.02777768243109202, 2.2524684225188576),
                  stops: [0.0, 1.0],
                  colors: [
                    Color.fromARGB(255, 246, 162, 172),
                    Color.fromARGB(193, 241, 199, 245)
                  ],
                ),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    Positioned(
                      left: 268.0,
                      top: 28.0,
                      right: null,
                      bottom: null,
                      width: 66.0,
                      height: 64.0,
                      child: GeneratedEllipse13Widget3(),
                    ),
                    Positioned(
                      left: 47.0,
                      top: 92.0,
                      right: null,
                      bottom: null,
                      width: 289.0,
                      height: 89.0,
                      child: GeneratedFindYourNearestOncologistWidget(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 370.0,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 80.0,
                      child: GeneratedImage25Widget(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 327.0,
                      right: null,
                      bottom: null,
                      width: 101.0,
                      height: 24.0,
                      child: GeneratedTopDoctorsWidget(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 471.0,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 80.0,
                      child: GeneratedImage26Widget(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 572.0,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 80.0,
                      child: GeneratedImage27Widget(),
                    ),
                    Positioned(
                      left: 302.0,
                      top: 338.0,
                      right: null,
                      bottom: null,
                      width: 41.0,
                      height: 15.0,
                      child: GeneratedViewallWidget(),
                    ),
                    Positioned(
                      left: 117.0,
                      top: 364.0,
                      right: null,
                      bottom: null,
                      width: 224.0,
                      height: 145.0,
                      child: GeneratedGroup1309Widget(),
                    ),
                    Positioned(
                      left: 117.0,
                      top: 466.0,
                      right: null,
                      bottom: null,
                      width: 224.0,
                      height: 77.0,
                      child: GeneratedGroup1310Widget(),
                    ),
                    Positioned(
                      left: 34.0,
                      top: 204.0,
                      right: null,
                      bottom: null,
                      width: 56.0,
                      height: 56.0,
                      child: GeneratedGroup1315Widget(),
                    ),
                    Positioned(
                      left: 120.0,
                      top: 566.0,
                      right: null,
                      bottom: null,
                      width: 226.0,
                      height: 77.0,
                      child: GeneratedGroup1311Widget(),
                    ),
                    Positioned(
                      left: 118.0,
                      top: 590.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 26.0,
                      child: GeneratedBreastsWidget3(),
                    ),
                    Positioned(
                      left: 114.0,
                      top: 203.0,
                      right: null,
                      bottom: null,
                      width: 56.0,
                      height: 57.0,
                      child: GeneratedGroup1316Widget(),
                    ),
                    Positioned(
                      left: 194.0,
                      top: 203.0,
                      right: null,
                      bottom: null,
                      width: 56.0,
                      height: 56.0,
                      child: GeneratedGroup1317Widget(),
                    ),
                    Positioned(
                      left: 29.0,
                      top: 264.0,
                      right: null,
                      bottom: null,
                      width: 73.0,
                      height: 26.0,
                      child: GeneratedConsultationWidget(),
                    ),
                    Positioned(
                      left: 116.0,
                      top: 264.0,
                      right: null,
                      bottom: null,
                      width: 54.0,
                      height: 26.0,
                      child: GeneratedHospitalsWidget(),
                    ),
                    Positioned(
                      left: 274.0,
                      top: 204.0,
                      right: null,
                      bottom: null,
                      width: 56.0,
                      height: 56.0,
                      child: GeneratedGroup1318Widget(),
                    ),
                    Positioned(
                      left: 194.0,
                      top: 264.0,
                      right: null,
                      bottom: null,
                      width: 59.0,
                      height: 26.0,
                      child: GeneratedMedicinesWidget(),
                    ),
                    Positioned(
                      left: 280.0,
                      top: 264.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 26.0,
                      child: GeneratedSurgeonWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 566.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup27Widget2(),
            )
          ]),
    ));
  }
}
