import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedTextWidget1.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedHereyoucanorganisesupportgroupsforpeoplewhohadsimilarex.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedCLICKHEREWidget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedDownloadremovebgpreview3Widget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedASAFESPACEFORSURVIVORSOFBREASTCANCERWidget.dart';
import 'package:flutterapp/pinkapp/generatedsupportgroupwidget/generated/GeneratedRectangle23Widget.dart';

/* Frame Support group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSupportgroupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: -1.3359375,
                top: 64.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 72.0,
                child: GeneratedASAFESPACEFORSURVIVORSOFBREASTCANCERWidget(),
              ),
              Positioned(
                left: 186.1484375,
                top: 420.0,
                right: null,
                bottom: null,
                width: 2.0,
                height: 26.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 186.1484375,
                top: 475.0,
                right: null,
                bottom: null,
                width: 2.0,
                height: 50.0,
                child: GeneratedTextWidget1(),
              ),
              Positioned(
                left: 134.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 34.0,
                child: GeneratedTextWidget2(),
              ),
              Positioned(
                left: 23.46875,
                top: 423.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 152.0,
                child:
                    GeneratedHereyoucanorganisesupportgroupsforpeoplewhohadsimilarex(),
              ),
              Positioned(
                left: 0.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: -51.46875,
                top: 154.0,
                right: null,
                bottom: null,
                width: 268.46875,
                height: 260.0,
                child: GeneratedDownloadremovebgpreview3Widget(),
              ),
              Positioned(
                left: 53.765625,
                top: 241.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 59.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 198.24853515625,
                top: 257.5,
                right: null,
                bottom: null,
                width: 142.22021484375,
                height: 42.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 196.85458374023438,
                top: 239.5,
                right: null,
                bottom: null,
                width: 145.5271453857422,
                height: 80.0,
                child: GeneratedCLICKHEREWidget(),
              ),
              Positioned(
                left: 149.00267028808594,
                top: 247.7216339111328,
                right: null,
                bottom: null,
                width: 61.0,
                height: 58.5,
                child: GeneratedImage13Widget(),
              )
            ]),
      ),
    ));
  }
}
