import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedWhatAretheSymptomsofBreastCancerWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedFrameWidget3.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedManyconditionscancauselumpsinthebreastincludingcancerBu.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedLine2Widget2.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedBREASTCANCERWidget2.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedGroup1Widget5.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedToreadmoreaboutBRCA1andBRCA2Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedDoctorsknowthatbreastcanceroccurswhensomebreastcellsbeg.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedCells1Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedFrameWidget4.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedDifferentpeoplehavedifferentsymptomsofbreastcancerSomep.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedBreastcancermostoftenbeginswithcellsinthemilkproducingd.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedSOMESIGNSINCLUDEWidget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/Generated03fb7c624dce984746a1feb0bcc0e5be1Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedDoctorsestimatethatabout5to10percentofbreastcancersarel.dart';
import 'package:flutterapp/pinkapp/generatedawareness2widget/generated/GeneratedRectangle13Widget3.dart';

/* Frame awareness-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAwareness2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1651.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1651.0,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.0, -1.0),
                                end: Alignment(0.0, 0.9999999999999998),
                                stops: [0.0, 1.0],
                                colors: [
                                  Color.fromARGB(255, 249, 155, 155),
                                  Color.fromARGB(196, 241, 199, 245)
                                ],
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  Positioned(
                                    left: 7.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 345.8785400390625,
                                    height: 778.0,
                                    child: GeneratedGroup19Widget1(),
                                  ),
                                  Positioned(
                                    left: 61.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 81.0,
                                    height: 44.0,
                                    child: GeneratedRectangle13Widget3(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 22.0,
                                    right: null,
                                    bottom: null,
                                    width: 288.0,
                                    height: 114.0,
                                    child: GeneratedBREASTCANCERWidget2(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 68.0,
                                    height: 1.0,
                                    child: GeneratedLine2Widget2(),
                                  ),
                                  Positioned(
                                    left: 291.0,
                                    top: 78.0,
                                    right: null,
                                    bottom: null,
                                    width: 69.0,
                                    height: 1.0,
                                    child: GeneratedLine3Widget1(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 154.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 120.0,
                                    child:
                                        GeneratedManyconditionscancauselumpsinthebreastincludingcancerBu(),
                                  ),
                                  Positioned(
                                    left: 23.0,
                                    top: 498.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 39.0,
                                    child:
                                        GeneratedDifferentpeoplehavedifferentsymptomsofbreastcancerSomep(),
                                  ),
                                  Positioned(
                                    left: 23.0,
                                    top: 541.0,
                                    right: null,
                                    bottom: null,
                                    width: 152.0,
                                    height: 23.0,
                                    child: GeneratedSOMESIGNSINCLUDEWidget(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 282.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 140.0,
                                    child:
                                        Generated03fb7c624dce984746a1feb0bcc0e5be1Widget(),
                                  ),
                                  Positioned(
                                    left: 83.0,
                                    top: 442.0,
                                    right: null,
                                    bottom: null,
                                    width: 204.0,
                                    height: 71.0,
                                    child:
                                        GeneratedWhatAretheSymptomsofBreastCancerWidget(),
                                  ),
                                  Positioned(
                                    left: 17.0,
                                    top: 811.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 140.0,
                                    child:
                                        GeneratedDoctorsknowthatbreastcanceroccurswhensomebreastcellsbeg(),
                                  ),
                                  Positioned(
                                    left: 123.0,
                                    top: 949.0,
                                    right: null,
                                    bottom: null,
                                    width: 221.0,
                                    height: 155.0,
                                    child:
                                        GeneratedBreastcancermostoftenbeginswithcellsinthemilkproducingd(),
                                  ),
                                  Positioned(
                                    left: 21.0,
                                    top: 1117.0,
                                    right: null,
                                    bottom: null,
                                    width: 153.0,
                                    height: 400.0,
                                    child:
                                        GeneratedDoctorsestimatethatabout5to10percentofbreastcancersarel(),
                                  ),
                                  Positioned(
                                    left: 200.0,
                                    top: 1227.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.83413696289062,
                                    height: 265.51239013671875,
                                    child: GeneratedFrameWidget3(),
                                  ),
                                  Positioned(
                                    left: 271.0,
                                    top: 1151.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.83413696289062,
                                    height: 265.51239013671875,
                                    child: GeneratedFrameWidget4(),
                                  ),
                                  Positioned(
                                    left: 260.0,
                                    top: 1592.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup1Widget4(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 953.0,
                                    right: null,
                                    bottom: null,
                                    width: 107.0,
                                    height: 149.0,
                                    child: GeneratedCells1Widget(),
                                  ),
                                  Positioned(
                                    left: 89.0,
                                    top: 1597.0,
                                    right: null,
                                    bottom: null,
                                    width: 184.0,
                                    height: 17.0,
                                    child:
                                        GeneratedToreadmoreaboutBRCA1andBRCA2Widget(),
                                  ),
                                  Positioned(
                                    left: 89.0,
                                    top: 1617.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 25.0,
                                    child: GeneratedGroup1Widget5(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 569.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup23Widget(),
            )
          ]),
    ));
  }
}
