import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedreminder0widget/generated/GeneratedMonthSelectorWidget1.dart';
import 'package:flutterapp/pinkapp/generatedreminder0widget/generated/GeneratedCalendarEventsWidget2.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame reminder0
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReminder0Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 635.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(7, 170, 170, 170),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 32.0,
                )
              ],
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.0, 1.0],
          colors: [
            Color.fromARGB(255, 249, 155, 155),
            Color.fromARGB(89, 241, 199, 245)
          ],
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 33.0,
              top: 41.0,
              right: null,
              bottom: null,
              width: 201.62741088867188,
              height: 29.0,
              child: GeneratedMonthSelectorWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 98.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 537.0,
              child: GeneratedCalendarEventsWidget2(),
            )
          ]),
    ));
  }
}
