import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedASIMPLEGUIDEONWidget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedINSUPPORTGROUPSWidget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedGetStartedWidget1.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedBREASTCANCERWidget1.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedFINDLIKEMINDEDPEOPLEWidget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedLayer2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/pinkapp/generatedhomepagewidget/generated/GeneratedRectangle5Widget1.dart';

/* Frame Homepage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 640.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 240, 175, 207),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 640.0,
                      child: GeneratedRectangle1Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 640.0,
                      child: GeneratedRectangle2Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.390625;

                        final double height = constraints.maxHeight * 0.20625;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.3333333333333333,
                              y: constraints.maxHeight * 0.0078125,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedLayer2Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 150.0,
                      top: 291.0,
                      right: null,
                      bottom: null,
                      width: 193.0,
                      height: 110.0,
                      child: GeneratedGroup5Widget(),
                    ),
                    Positioned(
                      left: 18.0,
                      top: 431.0,
                      right: null,
                      bottom: null,
                      width: 193.0,
                      height: 110.0,
                      child: GeneratedRectangle4Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 150.0,
                      right: null,
                      bottom: null,
                      width: 195.0,
                      height: 110.0,
                      child: GeneratedRectangle4Widget2(),
                    ),
                    Positioned(
                      left: 54.0,
                      top: 189.0,
                      right: null,
                      bottom: null,
                      width: 125.0,
                      height: 24.0,
                      child: GeneratedBREASTCANCERWidget1(),
                    ),
                    Positioned(
                      left: 55.0,
                      top: 173.0,
                      right: null,
                      bottom: null,
                      width: 124.0,
                      height: 18.0,
                      child: GeneratedASIMPLEGUIDEONWidget(),
                    ),
                    Positioned(
                      left: 72.375,
                      top: 218.0,
                      right: null,
                      bottom: null,
                      width: 87.0,
                      height: 20.0,
                      child: GeneratedRectangle5Widget1(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 218.0,
                      right: null,
                      bottom: null,
                      width: 27.0,
                      height: 20.0,
                      child: GeneratedGroup1Widget1(),
                    ),
                    Positioned(
                      left: 80.0,
                      top: 220.0,
                      right: null,
                      bottom: null,
                      width: 61.0,
                      height: 17.0,
                      child: GeneratedGetStartedWidget1(),
                    ),
                    Positioned(
                      left: 41.0,
                      top: 451.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 18.0,
                      child: GeneratedFINDLIKEMINDEDPEOPLEWidget(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 497.0,
                      right: null,
                      bottom: null,
                      width: 88.0,
                      height: 20.0,
                      child: GeneratedGroup6Widget(),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 467.0,
                      right: null,
                      bottom: null,
                      width: 162.0,
                      height: 24.0,
                      child: GeneratedINSUPPORTGROUPSWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 565.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup19Widget(),
            )
          ]),
    ));
  }
}
