import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedGroup26Widget4.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedImagesremovebgpreview2Widget.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedBeingdiagnosedwithbreastcancerandongoingtreatmentcancau.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedTREATMENTWidget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedGroup26Widget5.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedGroup25Widget6.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedForyogatechniquesgooddietandcalmingmusicWidget.dart';
import 'package:flutterapp/pinkapp/generatedtreatmentwidget/generated/GeneratedLine7Widget1.dart';

/* Frame Treatment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTreatmentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 672.0,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment(0.0, -1.0),
                  end: Alignment(0.0, 0.9999999999999998),
                  stops: [0.0, 1.0],
                  colors: [
                    Color.fromARGB(255, 252, 183, 183),
                    Color.fromARGB(206, 241, 199, 245)
                  ],
                ),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    Positioned(
                      left: 24.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 345.8785400390625,
                      height: 44.0,
                      child: GeneratedGroup26Widget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 78.0,
                      height: 44.0,
                      child: GeneratedRectangle16Widget2(),
                    ),
                    Positioned(
                      left: 6.0,
                      top: 265.0,
                      right: null,
                      bottom: null,
                      width: 350.0,
                      height: 353.0,
                      child:
                          GeneratedBeingdiagnosedwithbreastcancerandongoingtreatmentcancau(),
                    ),
                    Positioned(
                      left: 78.0,
                      top: 100.0,
                      right: null,
                      bottom: null,
                      width: 205.0,
                      height: 188.0,
                      child: GeneratedImagesremovebgpreview2Widget(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 22.0,
                      right: null,
                      bottom: null,
                      width: 291.0,
                      height: 117.0,
                      child: GeneratedTREATMENTWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 78.0,
                      right: null,
                      bottom: null,
                      width: 82.0,
                      height: 1.0,
                      child: GeneratedLine6Widget1(),
                    ),
                    Positioned(
                      left: 280.0,
                      top: 78.0,
                      right: null,
                      bottom: null,
                      width: 80.0,
                      height: 1.0,
                      child: GeneratedLine7Widget1(),
                    ),
                    Positioned(
                      left: 71.0,
                      top: 621.0,
                      right: null,
                      bottom: null,
                      width: 232.0,
                      height: 17.0,
                      child:
                          GeneratedForyogatechniquesgooddietandcalmingmusicWidget(),
                    ),
                    Positioned(
                      left: 296.0,
                      top: 616.0,
                      right: null,
                      bottom: null,
                      width: 27.0,
                      height: 25.0,
                      child: GeneratedGroup25Widget6(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 566.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 75.0,
              child: GeneratedGroup26Widget5(),
            )
          ]),
    ));
  }
}
