import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedGroup7Widget3.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedDonthaveanAccountSignUpWidget.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedEMAILADDRESSWidget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedEllipse1Widget7.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedRectangle2Widget8.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedCONNECTWITHFACEBOOKWidget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedSIGNUPWidget2.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedLOGINWidget2.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/pinkapp/generatedloginpagewidget/generated/GeneratedLine2Widget1.dart';

/* Frame Log in page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 124.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 17.0,
                child: GeneratedCONNECTWITHFACEBOOKWidget1(),
              ),
              Positioned(
                left: -39.0,
                top: -130.0,
                right: null,
                bottom: null,
                width: 424.0,
                height: 358.0,
                child: GeneratedEllipse1Widget7(),
              ),
              Positioned(
                left: 117.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 125.56462097167969,
                height: 64.0,
                child: GeneratedGroup7Widget3(),
              ),
              Positioned(
                left: 156.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 12.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 456.0,
                child: GeneratedRectangle1Widget8(),
              ),
              Positioned(
                left: 81.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 29.0,
                child: GeneratedDonthaveanAccountSignUpWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 18.0,
                child: GeneratedForgotPasswordWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 205.00244140625,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 76.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 76.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 32.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 76.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 29.0,
                child: GeneratedEMAILADDRESSWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 34.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 25.0,
                child: GeneratedRectangle2Widget8(),
              ),
              Positioned(
                left: 90.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 23.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 198.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedSIGNUPWidget2(),
              ),
              Positioned(
                left: 156.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 23.0,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 12.0,
                child: GeneratedLOGINWidget2(),
              )
            ]),
      ),
    ));
  }
}
