import 'package:flutter/material.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedWhileyouarelookingatthemirrorlookforanysignsoffluidcomi.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedNowletsmovetostep3Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedImage8Widget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedSELFEXAMINATIONWidget3.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedThiscouldbeawaterymilkyoryellowfluidorbloodWidget.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/pinkapp/generatedselfexam2widget/generated/GeneratedStep2Widget.dart';

/* Frame Self exam 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelfexam2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 175, 207),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget6(),
              ),
              Positioned(
                left: 68.5,
                top: 66.5,
                right: null,
                bottom: null,
                width: 225.0,
                height: 34.0,
                child: GeneratedSELFEXAMINATIONWidget3(),
              ),
              Positioned(
                left: 4.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 74.0,
                child:
                    GeneratedWhileyouarelookingatthemirrorlookforanysignsoffluidcomi(),
              ),
              Positioned(
                left: 19.798828125,
                top: 450.625,
                right: null,
                bottom: null,
                width: 322.0,
                height: 50.0,
                child:
                    GeneratedThiscouldbeawaterymilkyoryellowfluidorbloodWidget(),
              ),
              Positioned(
                left: 55.1494140625,
                top: 584.4225463867188,
                right: null,
                bottom: null,
                width: 249.701171875,
                height: 34.0,
                child: GeneratedRectangle21Widget2(),
              ),
              Positioned(
                left: 83.298828125,
                top: 589.4225463867188,
                right: null,
                bottom: null,
                width: 194.0,
                height: 26.0,
                child: GeneratedNowletsmovetostep3Widget(),
              ),
              Positioned(
                left: 147.298828125,
                top: 146.375,
                right: null,
                bottom: null,
                width: 67.0,
                height: 34.0,
                child: GeneratedStep2Widget(),
              ),
              Positioned(
                left: 115.798828125,
                top: 210.5625,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedImage8Widget(),
              )
            ]),
      ),
    ));
  }
}
